#!/usr/bin/env bash
# twatch one-line installer (Ubuntu / Debian).
#
# Remote install:
#   curl -fsSL https://raw.githubusercontent.com/ItzAmirreza/terminalwatch/main/install.sh | bash
#
# Local install (from a checkout):
#   ./install.sh
#
# Env overrides:
#   TWATCH_REPO       git URL (default: github.com/ItzAmirreza/terminalwatch.git)
#   TWATCH_BRANCH     branch / ref (default: main)
#   TWATCH_DIR        where to put the source (default: ~/.local/share/twatch)
#   TWATCH_BIN_DIR    where to write the launcher (default: /usr/local/bin)

set -euo pipefail

REPO_URL="${TWATCH_REPO:-https://github.com/ItzAmirreza/terminalwatch.git}"
BRANCH="${TWATCH_BRANCH:-main}"
INSTALL_DIR="${TWATCH_DIR:-$HOME/.local/share/twatch}"
BIN_DIR="${TWATCH_BIN_DIR:-/usr/local/bin}"
BIN_TARGET="$BIN_DIR/twatch"

say()   { printf "\033[36m==>\033[0m %s\n" "$*"; }
warn()  { printf "\033[33m!! \033[0m %s\n" "$*" >&2; }
fail()  { printf "\033[31mxx \033[0m %s\n" "$*" >&2; exit 1; }
ok()    { printf "\033[32m✓\033[0m  %s\n" "$*"; }

[ "$(uname -s)" = "Linux" ] || fail "twatch requires Linux (uses /proc + strace)."

# Detect run-from-checkout mode: if install.sh is sitting next to package.json
# with our binary listed, we install from here instead of cloning anything.
# When piped via `curl … | bash`, BASH_SOURCE is unset or "main"; treat that
# as remote-mode and skip the local-checkout probe.
SCRIPT_SRC="${BASH_SOURCE[0]:-}"
SCRIPT_DIR=""
if [ -n "$SCRIPT_SRC" ] && [ "$SCRIPT_SRC" != "main" ] && [ -e "$SCRIPT_SRC" ]; then
  SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$SCRIPT_SRC")")" && pwd)"
fi
LOCAL_MODE=no
if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/package.json" ] \
   && grep -q '"twatch"' "$SCRIPT_DIR/package.json" 2>/dev/null; then
  LOCAL_MODE=yes
fi

# 1. system prereqs
pkgs=()
command -v curl   >/dev/null || pkgs+=(curl)
command -v unzip  >/dev/null || pkgs+=(unzip)
command -v strace >/dev/null || pkgs+=(strace)
[ "$LOCAL_MODE" = "no" ] && ! command -v git >/dev/null && pkgs+=(git)

if [ "${#pkgs[@]}" -gt 0 ]; then
  if ! command -v apt-get >/dev/null; then
    fail "missing prerequisites (${pkgs[*]}) and no apt-get to install them. Install manually then retry."
  fi
  say "installing prerequisites: ${pkgs[*]}"
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${pkgs[@]}"
fi

# 2. bun
if ! command -v bun >/dev/null && [ ! -x "$HOME/.bun/bin/bun" ]; then
  say "installing bun"
  curl -fsSL https://bun.sh/install | bash >/dev/null
fi
BUN="$(command -v bun || true)"
[ -n "$BUN" ] || BUN="$HOME/.bun/bin/bun"
[ -x "$BUN" ] || fail "bun not found after install attempt."
ok "bun: $($BUN --version) at $BUN"

# 3. source
if [ "$LOCAL_MODE" = "yes" ]; then
  if [ "$SCRIPT_DIR" != "$INSTALL_DIR" ]; then
    say "copying local checkout to $INSTALL_DIR"
    mkdir -p "$(dirname "$INSTALL_DIR")"
    rm -rf "$INSTALL_DIR"
    cp -R "$SCRIPT_DIR" "$INSTALL_DIR"
  else
    say "using in-place checkout at $INSTALL_DIR"
  fi
else
  if [ -d "$INSTALL_DIR/.git" ]; then
    say "updating existing checkout at $INSTALL_DIR"
    git -C "$INSTALL_DIR" fetch --depth 1 origin "$BRANCH"
    git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH"
  else
    say "cloning $REPO_URL → $INSTALL_DIR"
    mkdir -p "$(dirname "$INSTALL_DIR")"
    git clone --depth 1 -b "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
  fi
fi

# 4. JS deps
say "installing dependencies (bun install)"
( cd "$INSTALL_DIR" && "$BUN" install --silent )

# 5. system launcher
say "installing launcher → $BIN_TARGET"
if ! sudo -n true 2>/dev/null && [ ! -w "$BIN_DIR" ]; then
  warn "sudo will prompt for your password to write $BIN_TARGET"
fi
sudo tee "$BIN_TARGET" >/dev/null <<EOF
#!/usr/bin/env bash
# auto-generated by twatch installer
exec "$BUN" run "$INSTALL_DIR/src/index.tsx" "\$@"
EOF
sudo chmod +x "$BIN_TARGET"

# Refresh shell hash so 'twatch' is callable in the *current* shell too.
hash -r 2>/dev/null || true

echo
ok "twatch installed."
echo "    run:     twatch"
echo "    source:  $INSTALL_DIR"
echo "    bun:     $BUN"
echo
warn "twatch invokes sudo strace internally; make sure this user has sudo (passwordless or interactive)."
