#!/usr/bin/env bash
# twatch one-line installer (Ubuntu / Debian).
#
# Remote install (the headline one-liner):
#   curl -fsSL https://raw.githubusercontent.com/ItzAmirreza/terminalwatch/main/install.sh | bash
#
# What it does, end-to-end:
#   1. apt-installs `curl unzip strace` if any are missing
#   2. installs Bun (https://bun.sh) if `bun` isn't on $PATH already
#   3. `bun i -g terminalwatch`  (or the version pinned in $TWATCH_VERSION)
#   4. drops a /usr/local/bin/twatch shim so the command is on PATH for
#      every shell on the box, regardless of whether the caller's PATH
#      includes ~/.bun/bin
#
# This routes everyone through the npm-installed package, so the
# in-app auto-updater can do `bun add -g terminalwatch@latest`
# without us having to maintain a separate git-clone topology.
#
# Local install (from a checkout) is still supported — run ./install.sh
# from inside the repo and it `bun link`s the checkout instead of
# fetching from npm.
#
# Env overrides:
#   TWATCH_VERSION    pin a specific npm version (default: latest)
#   TWATCH_BIN_DIR    where to write the launcher (default: /usr/local/bin)

set -euo pipefail

PKG_NAME="terminalwatch"
PKG_SPEC="${PKG_NAME}@${TWATCH_VERSION:-latest}"
BIN_DIR="${TWATCH_BIN_DIR:-/usr/local/bin}"
BIN_TARGET="$BIN_DIR/twatch"

say()   { printf "\033[36m==>\033[0m %s\n" "$*"; }
warn()  { printf "\033[33m!! \033[0m %s\n" "$*" >&2; }
fail()  { printf "\033[31mxx \033[0m %s\n" "$*" >&2; exit 1; }
ok()    { printf "\033[32m✓\033[0m  %s\n" "$*"; }

[ "$(uname -s)" = "Linux" ] || fail "twatch requires Linux (uses /proc + strace)."

# Detect run-from-checkout mode: when install.sh sits next to a
# package.json whose bin field claims `twatch`. We use `bun link` so the
# local source becomes the globally-installed copy and stays editable.
SCRIPT_SRC="${BASH_SOURCE[0]:-}"
SCRIPT_DIR=""
if [ -n "$SCRIPT_SRC" ] && [ "$SCRIPT_SRC" != "main" ] && [ -e "$SCRIPT_SRC" ]; then
  SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$SCRIPT_SRC")")" && pwd)"
fi
LOCAL_MODE=no
if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/package.json" ] \
   && grep -q '"twatch"' "$SCRIPT_DIR/package.json" 2>/dev/null; then
  LOCAL_MODE=yes
fi

# 1. system prereqs
pkgs=()
command -v curl   >/dev/null || pkgs+=(curl)
command -v unzip  >/dev/null || pkgs+=(unzip)
command -v strace >/dev/null || pkgs+=(strace)

if [ "${#pkgs[@]}" -gt 0 ]; then
  if ! command -v apt-get >/dev/null; then
    fail "missing prerequisites (${pkgs[*]}) and no apt-get to install them. Install manually then retry."
  fi
  say "installing prerequisites: ${pkgs[*]}"
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${pkgs[@]}"
fi

# 2. Bun
if ! command -v bun >/dev/null && [ ! -x "$HOME/.bun/bin/bun" ]; then
  say "installing bun"
  curl -fsSL https://bun.sh/install | bash >/dev/null
fi
BUN="$(command -v bun || true)"
[ -n "$BUN" ] || BUN="$HOME/.bun/bin/bun"
[ -x "$BUN" ] || fail "bun not found after install attempt."
ok "bun: $($BUN --version) at $BUN"

# 3. terminalwatch — same `bun add -g` topology in both modes; in local
#    mode we feed bun the filesystem path of the checkout instead of the
#    npm spec, so the in-app `u` upgrader still works (`bun add -g
#    terminalwatch@latest` will fetch from npm next time, transparently
#    replacing the local install).
if [ "$LOCAL_MODE" = "yes" ]; then
  say "installing from local checkout at $SCRIPT_DIR (bun add -g .)"
  ( cd "$SCRIPT_DIR" && "$BUN" install --silent )
  "$BUN" add -g "$SCRIPT_DIR"
else
  say "installing $PKG_SPEC from npm (bun i -g)"
  "$BUN" add -g "$PKG_SPEC"
fi

# 4. resolve where bun put the launcher
BUN_BIN="$(dirname "$BUN")"
USER_TWATCH="$BUN_BIN/twatch"
[ -x "$USER_TWATCH" ] || fail "bun installed terminalwatch but didn't drop a twatch binary at $USER_TWATCH"
ok "bun bin: $USER_TWATCH"

# 5. system-wide launcher — a tiny shim so /usr/local/bin/twatch resolves
#    regardless of $PATH ordering (cron, non-login shells, ssh -c, etc.)
say "installing launcher → $BIN_TARGET"
if ! sudo -n true 2>/dev/null && [ ! -w "$BIN_DIR" ]; then
  warn "sudo will prompt for your password to write $BIN_TARGET"
fi
sudo tee "$BIN_TARGET" >/dev/null <<EOF
#!/usr/bin/env bash
# auto-generated by twatch installer — forwards to the bun-managed
# install so \`u\` in-app upgrades land here too.
exec "$USER_TWATCH" "\$@"
EOF
sudo chmod +x "$BIN_TARGET"

# Refresh shell hash so 'twatch' is callable in the *current* shell too.
hash -r 2>/dev/null || true

# Detect and warn about any stale git-clone style install left over from
# install.sh versions < 0.4.1.
OLD_DIR="$HOME/.local/share/twatch"
if [ -d "$OLD_DIR" ]; then
  warn "leftover git-clone install at $OLD_DIR — safe to delete:"
  echo "    rm -rf $OLD_DIR"
fi

INSTALLED_VERSION="$("$USER_TWATCH" --version 2>/dev/null || true)"

echo
ok "twatch installed."
echo "    run:           twatch"
echo "    package:       $PKG_NAME${INSTALLED_VERSION:+ ($INSTALLED_VERSION)}"
echo "    bun:           $BUN"
echo "    update later:  press \`u\` in the TUI, or \`bun add -g $PKG_NAME@latest\`"
echo
warn "twatch invokes sudo strace internally; make sure this user has sudo (passwordless or interactive)."
